config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dekita/', include('dekita.urls')),
    path('admin/', admin.site.urls),
]

dekita/urls.py
from django.urls import path
from . import views

app_name = "dekita"
urlpatterns = [
    path('', views.index, name='index'),
    path("add/", views.add, name="add"),
    path("<int:todo_id>/edit/", views.edit, name="edit"),
    path("<int:todo_id>/done/", views.done, name="done"),
    path("add_category/", views.add_category, name="add_category"),
    path("<int:cate_id>/edit_category/", views.edit_category, name="edit_category"),
    path("<int:do_id>/add_do/", views.add_do, name="add_do"),
]

dekita/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Do(models.Model):
    do_text = models.CharField(max_length=200)

    def __str__(self):
        return self.do_text

class Category(models.Model):
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.category


def default_category():
    category, _ = Category.objects.get_or_create(category='default')
    # idを返す
    return category.id


class ToDoList(models.Model):
    category = models.ForeignKey(
        Category, default=default_category, on_delete=models.CASCADE)
    todolist = models.CharField(max_length=200)
    wayoflearning = models.CharField(max_length=200, default="")
    created_at = models.DateTimeField(default=timezone.now)
    displayflag = models.BooleanField(default=True)


    def __str__(self):
        return self.todolist


class DoneList(models.Model):
    done_text = models.CharField(max_length=30)

dekita/forms.py
from django import forms
from .models import ToDoList, Category, Do


class AddForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ("category",
                  "todolist",
                  "wayoflearning",)


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("category",)


class AddDoForm(forms.ModelForm):
    class Meta:
        model = Do
        fields = ("do_text",)

dekita/views.py
from django.urls import reverse
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from dekita.models import ToDoList, Category, Do
from dekita.forms import AddForm, AddCategoryForm, AddDoForm


# Create your views here.


def index(request):
    todolist = ToDoList.objects.order_by("created_at")
    category = Category.objects.all()
    try:
        do = Do.objects.get(id=1)
    except:
        do = "固定メモを書き込む"
    context = {"todolist": todolist,
               "category": category,
               "do": do}

    return render(request, 'dekita/index.html', context)


def add(request):

    if request.method == "POST":
        form = AddForm(request.POST)
        if form.is_valid:
            form.save()
    else:
        form = AddForm()
    context = {"form": form}

    return render(request, 'dekita/add.html', context)


def add_category(request):

    if request.method == "POST":
        form = AddCategoryForm(request.POST)
        if form.is_valid:
            form.save()
    else:
        form = AddCategoryForm()

    # 以下、カテゴリ追加ページで全カテゴリ編集ってのをやりたかったが無理なので取り下げ。
    # 全カテゴリを編集可能なフォームの形で送りつける。
    #try:
    #    category_list = Category.objects.all()
    #except Category.DoesNotExist:
    #    raise Http404

    #form_list = []
    #for category in category_list:
    #    form_list.append(AddCategoryForm(instance=category))

    context = {"form": form,}
    #           "form_list": form_list}
    # コメントアウト終了

    return render(request, 'dekita/add_category.html', context)


def add_do(request, do_id):
    try:
        do = Do.objects.get(id=do_id)
        if request.method == 'POST':
            form = AddDoForm(request.POST, instance=do)
            if form.is_valid:
                form.save()
                return HttpResponseRedirect(reverse('dekita:add_do',
                                         args=(do.id,)))
        else:
            form = AddDoForm(instance=do)
    # 初回で固定メモを作成するときはexceptの内容
    except:
        if request.method == "POST":
            form = AddDoForm(request.POST)
            if form.is_valid:
                form.save()
        else:
            form = AddDoForm()

    context = {"form": form,}

    return render(request, 'dekita/add_do.html', context)


def edit_category(request, cate_id):
    try:
        cate = Category.objects.get(id=cate_id)
    except Category.DoesNotExist:
        raise Http404

    if request.method == "POST":
        form = AddCategoryForm(request.POST, instance=cate)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('dekita:edit_category',
                                         args=(cate.id,)))
    else:
        form = AddCategoryForm(instance=cate)

    context = {"form": form,}
    return TemplateResponse(request, "dekita/edit_category.html", context)


def edit(request, todo_id):
    try:
        todo = ToDoList.objects.get(id=todo_id)
    except ToDoList.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = AddForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dekita:edit',
                                                args=(todo.id,)))
    else:
        form = AddForm(instance=todo)

        return TemplateResponse(request, "dekita/edit.html", {"form": form,
                                                              "todo": todo})


def done(request, todo_id):
    try:
        todolist = ToDoList.objects.get(id=todo_id)
    except ToDoList.DoesNotExist:
        raise Http404

    # if request.method == 'POST':
        # todolistの内容を完了リストに移す
    todolist.delete()
    return HttpResponseRedirect(reverse('dekita:index'))
    # else:
    #    return TemplateResponse(request, 'dekita:index')

templates/dekita/add.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>dekita! - 編集画面</title>
</head>
<body>

<form action="{%url 'dekita:add' %}" method="post">
    {% csrf_token %}
    <p>dekita! - できたことをメモしよう</p>

    {{ form.as_p }}
    <input type="submit" value="dekita!">

</form>

<a href="{% url 'dekita:index' %}" >戻る</a>

</body>
</html>

templates/dekita/add_category.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>dekita! - 編集画面</title>
    <!-- いつかdetail画面に変更する -->
</head>
<body>

<form method="post">
    {% csrf_token %}
    <p>dekita! - カテゴリの追加</p>

    {{ form.as_p }}
    <input type="submit" value="add_category">

</form>

<!--  以下、カテゴリ追加画面に既存のカテゴリを並べ、
全て編集・削除できるようにするつもりだったがうまくいかなかったため一旦コメントアウト。
カテゴリ個々に編集削除ページを付け足すが、いつかここも実現させたい。

{% for cate in form_list %}
{{ cate.id }}
<form action="{% url 'dekita:edit_category' cate.id %}" method="post">
    {% csrf_token %}
    {{ cate.as_p }}
    <input type="submit" value="edit_category">
</form>
{% endfor %}
-->

<a href="{% url 'dekita:index' %}" >戻る</a>

</body>
</html>

templates/dekita/add_do.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>固定メモ</title>
</head>
<body>


<form action="{%url 'dekita:add_do' 1 %}" method="post">
    {% csrf_token %}
    <p>固定メモの編集</p>

    {{ form.as_p }}
    <input type="submit" value="メモする">

</form>


<a href="{% url 'dekita:index' %}" >戻る</a>

</body>
</html>

templates/dekita/edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>dekita! - 編集画面</title>
    <!-- いつかdetail画面に変更する -->
</head>
<body>

<form method="post">
    {% csrf_token %}
    <p>dekita! - できたことをメモしよう</p>

    {{ form.as_p }}
    <input type="submit" value="edit">

</form>

<form action="{% url 'dekita:done' todo.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="done!">
</form>
<a href="{% url 'dekita:index' %}" >戻る</a>

</body>
</html>

templates/dekita/edit_category.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>dekita! - カテゴリ編集画面</title>
    <!-- いつかdetail画面に変更する -->
</head>
<body>

<form method="post">
    {% csrf_token %}
    <p>dekita! - カテゴリの編集</p>

    {{ form.as_p }}
    <input type="submit" value="edit_category">

</form>

<a href="{% url 'dekita:index' %}" >戻る</a>

</body>
</html>

templates/dekita/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>デケエ板</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dekita/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'dekita/style.css' %}" />
    <style type="text/css"></style>
</head>


<body>
    <header class="header">
        <div class="header-wrapper clearfix">
            <p>障害対応発生！ 至急コードを修正してデプロイ</p>
            <h1 class="title">デケエ板...ver 0.01安定稼働版</h1>
            <p>ver 0.002に向け開発中...</p>
            <p>ver 0.02が正式発表。障害対応前後の開発と、障害対応のコードが全て盛り込まれている</p>
            <p>間違えてトラブルにあげちゃったけどまあいっか</p>
            <a class="todo-add" href="{% url 'dekita:add' %}">書き込む</a>
            <a class="category-add" href="{% url 'dekita:add_category' %}">カテゴリ追加</a>
        </div>
    </header>


    <div class="board-wrapper">
        <div class="board">
            <h1 class="top-category">固定メモ</h1>
            <a class="top-memo" href="{% url 'dekita:add_do' 1 %}">
                <p class="memo-text">
                    {{ do.do_text }}
                </p>
            </a>
        </div>
    </div>


    <div class="wrapper">
        <div class="main">
            {% for cate in category %}
            <a class="category-edit" href="{% url 'dekita:edit_category' cate.id %}">
                <h1 class="category">{{ cate }}</h1>
            </a>
            <ol class="contents">
                {% for todo in cate.todolist_set.all %}
                <li class="todo-edit">
                    <a href="{% url 'dekita:edit' todo.id %}">
                        <span class="todo-number"></span>
                        <p class="todo-text">
                            {{ todo.todolist|linebreaksbr }}
                        </p>
                    </a>
                </li>
                {% endfor %}
            </ol>
            {% endfor %}
        </div>
    </div>

</body>
</html>